#!/usr/bin/env node
/**
 * QazGost AI — Simple JS Bundler
 * Объединяет все локальные JS-файлы в один бандл (app.bundle.js)
 * Сохраняет порядок загрузки из index.html
 * 
 * Использование: node build.js
 * Результат: dist/app.bundle.js + dist/index.html
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const SRC_DIR = __dirname;
const DIST_DIR = path.join(__dirname, 'dist');
const INDEX_HTML = path.join(SRC_DIR, 'index.html');
const BUNDLE_NAME = 'app.bundle.js';

// ========== 1. Parse index.html ==========
console.log('📦 QazGost AI Bundler');
console.log('='.repeat(50));

const html = fs.readFileSync(INDEX_HTML, 'utf-8');

// Extract all <script src="..."> tags
const scriptRegex = /<script\s+[^>]*src="([^"]+)"[^>]*>\s*<\/script>/g;
const allScripts = [];
let match;

while ((match = scriptRegex.exec(html)) !== null) {
    const src = match[1];
    const fullTag = match[0];
    const isDefer = fullTag.includes('defer');
    const isExternal = src.startsWith('http://') || src.startsWith('https://');
    
    allScripts.push({ src, fullTag, isDefer, isExternal });
}

console.log(`\n📋 Found ${allScripts.length} script tags total`);

const externalScripts = allScripts.filter(s => s.isExternal);
const localScripts = allScripts.filter(s => !s.isExternal);

console.log(`   ├─ ${externalScripts.length} external (CDN)`);
console.log(`   └─ ${localScripts.length} local (will be bundled)`);

// ========== 2. Check all local files exist ==========
const missing = [];
const existing = [];

for (const script of localScripts) {
    const filePath = path.join(SRC_DIR, script.src);
    if (fs.existsSync(filePath)) {
        existing.push({ ...script, filePath });
    } else {
        missing.push(script.src);
    }
}

if (missing.length > 0) {
    console.log(`\n⚠️  Missing files (${missing.length}):`);
    missing.forEach(f => console.log(`   ✗ ${f}`));
}

// ========== 3. Deduplicate (same file included twice) ==========
const seen = new Set();
const dedupedScripts = [];

for (const script of existing) {
    const normalized = path.normalize(script.src);
    if (!seen.has(normalized)) {
        seen.add(normalized);
        dedupedScripts.push(script);
    } else {
        console.log(`   ⏭ Skipping duplicate: ${script.src}`);
    }
}

console.log(`\n📁 Bundling ${dedupedScripts.length} unique files...`);

// ========== 4. Concatenate into bundle ==========
const parts = [];
let totalSize = 0;

// Add banner
parts.push(`/**
 * QazGost AI — Bundled Application
 * Generated: ${new Date().toISOString()}
 * Files: ${dedupedScripts.length}
 * 
 * DO NOT EDIT — this file is auto-generated by build.js
 */
`);

for (const script of dedupedScripts) {
    const content = fs.readFileSync(script.filePath, 'utf-8');
    totalSize += content.length;
    
    parts.push(`\n// ========== ${script.src} ==========`);
    parts.push(content);
    parts.push(''); // blank line separator
}

const bundle = parts.join('\n');

// ========== 5. Write bundle ==========
if (!fs.existsSync(DIST_DIR)) {
    fs.mkdirSync(DIST_DIR, { recursive: true });
}

const bundlePath = path.join(DIST_DIR, BUNDLE_NAME);
fs.writeFileSync(bundlePath, bundle, 'utf-8');

const bundleSize = Buffer.byteLength(bundle, 'utf-8');
const savedPercent = ((1 - bundleSize / totalSize) * 100).toFixed(1);

console.log(`\n✅ Bundle created: dist/${BUNDLE_NAME}`);
console.log(`   ├─ Size: ${(bundleSize / 1024).toFixed(1)} KB`);
console.log(`   ├─ Original: ${(totalSize / 1024).toFixed(1)} KB across ${dedupedScripts.length} files`);
console.log(`   └─ HTTP requests saved: ${dedupedScripts.length - 1}`);

// ========== 6. Generate dist/index.html ==========
let distHtml = html;

// Remove all local script tags (keep external CDN ones)
for (const script of localScripts) {
    // Escape special regex chars in the tag
    const escapedTag = script.fullTag.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    distHtml = distHtml.replace(new RegExp(`\\s*${escapedTag}\\s*`, 'g'), '\n');
}

// Also remove the CatalogLoader preload inline script block
distHtml = distHtml.replace(
    /\s*<script>\s*document\.addEventListener\('DOMContentLoaded',\s*function\(\)\s*\{[\s\S]*?CatalogLoader\.preloadCommon[\s\S]*?<\/script>/,
    ''
);

// Insert single bundle reference before </body>
const bundleTag = `    <!-- Bundled application JS -->\n    <script src="${BUNDLE_NAME}"></script>`;
distHtml = distHtml.replace('</body>', `${bundleTag}\n</body>`);

// Clean up excessive blank lines
distHtml = distHtml.replace(/\n{4,}/g, '\n\n');

const distHtmlPath = path.join(DIST_DIR, 'index.html');
fs.writeFileSync(distHtmlPath, distHtml, 'utf-8');

console.log(`✅ dist/index.html created (${(Buffer.byteLength(distHtml, 'utf-8') / 1024).toFixed(1)} KB)`);

// ========== 7. Copy static assets ==========
const staticDirs = ['ai', 'vip', 'volume', 'chat', 'notifications', 'catalog', 'photogrammetry'];

// Copy catalogLazyLoader catalog files (wrk_*, mat_*, eq_* if they exist)
const catalogPatterns = ['wrk_', 'mat_', 'eq_', 'work_'];
let catalogCount = 0;

for (const entry of fs.readdirSync(SRC_DIR)) {
    if (catalogPatterns.some(p => entry.startsWith(p)) && entry.endsWith('.js')) {
        const src = path.join(SRC_DIR, entry);
        const dest = path.join(DIST_DIR, entry);
        fs.copyFileSync(src, dest);
        catalogCount++;
    }
}

if (catalogCount > 0) {
    console.log(`✅ Copied ${catalogCount} catalog files (for lazy-loading)`);
}

// Copy CSS files
const cssFiles = fs.readdirSync(SRC_DIR)
    .filter(f => f.endsWith('.css'));
for (const cssFile of cssFiles) {
    fs.copyFileSync(path.join(SRC_DIR, cssFile), path.join(DIST_DIR, cssFile));
}
console.log(`✅ Copied ${cssFiles.length} CSS files`);

// Copy images/icons if present
for (const dir of ['images', 'icons', 'assets']) {
    const dirPath = path.join(SRC_DIR, dir);
    if (fs.existsSync(dirPath)) {
        copyDirSync(dirPath, path.join(DIST_DIR, dir));
        console.log(`✅ Copied ${dir}/`);
    }
}

// Copy AI data files that are loaded dynamically
const aiDataDir = path.join(SRC_DIR, 'ai', 'data');
if (fs.existsSync(aiDataDir)) {
    const distAiDataDir = path.join(DIST_DIR, 'ai', 'data');
    if (!fs.existsSync(distAiDataDir)) {
        fs.mkdirSync(distAiDataDir, { recursive: true });
    }
    for (const f of fs.readdirSync(aiDataDir)) {
        fs.copyFileSync(path.join(aiDataDir, f), path.join(distAiDataDir, f));
    }
}

console.log('\n' + '='.repeat(50));
console.log(`🚀 Build complete! Serve dist/ folder.`);
console.log(`   Before: ${allScripts.length} HTTP requests`);
console.log(`   After:  ${externalScripts.length + 1} HTTP requests (${externalScripts.length} CDN + 1 bundle)`);
console.log(`   Saved:  ~${dedupedScripts.length - 1} network requests per page load`);

// ========== Helper: recursive copy dir ==========
function copyDirSync(src, dest) {
    if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src)) {
        const srcPath = path.join(src, entry);
        const destPath = path.join(dest, entry);
        if (fs.statSync(srcPath).isDirectory()) {
            copyDirSync(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    }
}
